# ROS2 Control Configuration File
#
# This config file uses placeholders that are replaced at launch time:
#
# <robot_namespace_prefix> - Combined namespace/prefix from launch args (e.g., "robot1/jackal_") - matches URDF joint/frame definitions
# <robot_prefix>           - Prefix from launch args (e.g., "jackal_")
#
# Note: Arm controllers are configured separately in the arms_bringup package
# https://github.com/MOBILAB-UDESC/arms.git

/**/controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

/**/diff_drive_base_controller:
  ros__parameters:
    type: diff_drive_controller/DiffDriveController
    left_wheel_names: ["<robot_namespace_prefix>rear_left_wheel", "<robot_namespace_prefix>front_left_wheel"]
    right_wheel_names: ["<robot_namespace_prefix>rear_right_wheel", "<robot_namespace_prefix>front_right_wheel"]

    wheel_separation: 0.37559
    wheels_per_side: 1
    wheel_radius: 0.098

    wheel_separation_multiplier: 1.5
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    publish_rate: 50.0
    odom_frame_id: <robot_prefix>odom
    base_frame_id: <robot_prefix>base_link
    # pose_covariance_diagonal : [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 0.03]
    # twist_covariance_diagonal: [0.001, 0.001, 0.001, 1000000.0, 1000000.0, 0.001]

    open_loop: false
    enable_odom_tf: false  # EKF will publish the tf

    cmd_vel_timeout: 0.25
    #publish_limited_velocity: true
    #velocity_rolling_window_size: 10

    # Velocity and acceleration limits
    linear.x.has_velocity_limits: true
    linear.x.max_velocity: 2.0
    linear.x.min_velocity: -2.0
    linear.x.has_acceleration_limits: true
    linear.x.max_acceleration: 20.0
    linear.x.min_acceleration: -20.0

    angular.z.has_velocity_limits: true
    angular.z.max_velocity: 4.0
    angular.z.min_velocity: -4.0
    angular.z.has_acceleration_limits: true
    angular.z.max_acceleration: 25.0
    angular.z.min_acceleration: -25.0